---
- name: create db_name
  hosts: localhost
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: create a new database
      mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: "{{ root_password }}"

    - name: copy data.sql to the target machine
      copy:
        src: "{{ lookup('env', 'IMPULSAPP_PATH') }}/data.sql"
        dest: /tmp/data.sql

    - name: copy user_priv.sql to the target machine
      copy:
        src: "{{ lookup('env', 'IMPULSAPP_PATH') }}/user_priv.sql"
        dest: /tmp/user_priv.sql

    - name: Insert data into the database
      command: >
        mysql --login-path=local {{ db_name }} < /tmp/data.sql


    - name: grant privileges to the user
      command: >
        mysql --login-path=local {{ db_name }} < /tmp/user_priv.sql


