- hosts: localhost
 become: yes
 tasks:
   - name: Download Node.js version 12
     get_url:
       url: https://nodejs.org/dist/v12.22.7/node-v12.22.7-linux-x64.tar.xz
       dest: /tmp/node-v12.22.7-linux-x64.tar.xz

   - name: Extract Node.js tarball
     unarchive:
       src: /tmp/node-v12.22.7-linux-x64.tar.xz
       dest: /opt
       remote_src: yes

   - name: Remove downloaded tarball
     file:
       path: /tmp/node-v12.22.7-linux-x64.tar.xz
       state: absent

   - name: Create symbolic link for node and npm
     file:
       src: /opt/node-v12.22.7-linux-x64/bin/node
       dest: /usr/bin/node
       state: link
       force: yes
     notify: Restart SSH

   - name: Create symbolic link for node and npm
     file:
       src: /opt/node-v12.22.7-linux-x64/bin/npm
       dest: /usr/bin/npm
       state: link
       force: yes

 handlers:
   - name: Restart SSH
     service:
       name: ssh
       state: restarted
