---
- hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        
    - name: Install the gpg key for NodeSource
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Add NodeSource repository for Node.js 14.x
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install Node.js version 14.x
      apt:
        name: nodejs
        state: present

    - name: Verify Node.js installation
      command: "node -v && npm -v"
