---
- hosts: localhost
  become: yes
  tasks:
    - name: Add NodeSource repo for Node.js 12.x
      shell: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -

    - name: Install Node.js 12.x
      apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Check Node.js version
      command: node -v
      register: node_version
      changed_when: false

    - debug:
        msg: "Node.js version installed is {{ node_version.stdout }}"
