---
- name: Install PHP CLI
  hosts: localhost
  become: yes 

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install PHP CLI
      package:
        name: php-cli
        state: present
      become: yes
