---
- hosts: localhost
  become: yes
  vars:
    symfony_project_dir: /var/www/symfony

  tasks:
    - name: Install PHP and necessary PHP extensions
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - php
        - php-xml
        - php-mbstring
        - php-zip
        - php-cli
        - php-curl
        - php-intl
        - php-gd
        - php-fpm
        - php-opcache
        - php-json

    - name: Download Composer installer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/composer-setup.php
        mode: '0755'

    - name: Install Composer globally
      command: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
      args:
        creates: /usr/local/bin/composer

    - name: Add non-root user for running Composer
      user:
        name: symfony_user
        system: yes
        home: "{{ symfony_project_dir }}"

    - name: Ensure Symfony project directory exists and is empty
      file:
        path: "{{ item }}"
        state: absent
      with_fileglob:
        - "{{ symfony_project_dir }}/*"

    - name: Create Symfony project directory
      file:
        path: "{{ symfony_project_dir }}"
        state: directory
        owner: symfony_user
        group: www-data
