---
- name: Configure Apache Virtual Hosts
  hosts: localhost
  become: yes

  tasks:
    - name: Copy and configure first virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/000-default.conf"
        dest: /etc/apache2/sites-available/000-default.conf
      notify:
        - Reload Apache

    - name: Enable first virtual host
      command: "a2ensite 000-default.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache

    - name: Copy and configure second virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/api.conf"
        dest: /etc/apache2/sites-available/api.conf
      notify:
        - Reload Apache

    - name: Enable second virtual host
      command: "a2ensite api.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache

    - name: Copy and configure third virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/default-ssl.conf"
        dest: /etc/apache2/sites-available/default-ssl.conf
      notify:
        - Reload Apache

    - name: Enable third virtual host
      command: "a2ensite default-ssl.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache

    - name: Copy and configure fourth virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/front.conf"
        dest: /etc/apache2/sites-available/front.conf
      notify:
        - Reload Apache

    - name: Enable fourth virtual host
      command: "a2ensite front.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache



  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
