- name: Configure Apache Virtual Hosts
  hosts: localhost
  become: yes

  tasks:
    - name: Enable proxy module
      command: a2enmod proxy
      become: yes

    - name: Enable proxy_http module
      command: a2enmod proxy_http
      become: yes

    - name: Disable default Apache site
      command: a2dissite 000-default.conf

    - name: Reload Apache to apply changes
      command: systemctl reload apache2

    - name: Copy and configure first virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/api.conf"
        dest: /etc/apache2/sites-available/api.conf
      notify:
        - Reload Apache

    - name: Enable second virtual host
      command: "a2ensite api.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache

    - name: Copy and configure third virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/front.conf"
        dest: /etc/apache2/sites-available/front.conf
      notify:
        - Reload Apache

    - name: Enable third virtual host
      command: "a2ensite front.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
