---
- name: Configure Apache Virtual Hosts
  hosts: localhost
  become: yes

  tasks:
    - name: disable default Apache site
      ansible.builtin.command: "/usr/sbin/a2dissite 000-default.conf"
      when: disable_default
      notify: reload Apache

      
    - name: Copy and configure first virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/api.conf"
        dest: /etc/apache2/sites-available/api.conf
      notify:
        - Reload Apache

    - name: Enable second virtual host
      command: "a2ensite api.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache

    - name: Copy and configure third virtual host
      template:
        src: "{{ lookup('env', 'full_path') }}/front.conf"
        dest: /etc/apache2/sites-available/front.conf
      notify:
        - Reload Apache

    - name: Enable third virtual host
      command: "a2ensite front.conf"
      args:
        chdir: /etc/apache2/sites-available/
      notify:
        - Reload Apache



  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
