stages:
  - validate
  - plan
  - apply

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init
    - sed -i "38s|.*|git_token=${git_token}|" custom_data.sh
    - sed -i "39s|.*|git_username=${git_username}|" custom_data.sh
    - sed -i "40s|.*|git clone https://\$git_username:\$git_token@github.com/Impulsa-fr/back-end.git|" custom_data.sh
    - sed -i "41s|.*|git clone https://\$git_username:\$git_token@github.com/Impulsa-fr/front-end.git|" custom_data.sh
    
    - sed -i '60s/.*/admin_password:${password}/' custom_data.sh
    - sed -i '61s/.*/DBPASS=${password}/' custom_data.sh
    - sed -i '62s/.*/URI_FRONT_HOME=${URI_FRONT_HOME}/' custom_data.sh
    - sed -i '63s/.*/URI_API=${URI_API}/' custom_data.sh
    - sed -i '64s/.*/DB_LOGIN=${DB_LOGIN}/' custom_data.sh
    - sed -i '65s/.*/DB_NAME=${DB_NAME}/' custom_data.sh
    - sed -i '66s/.*/domain_name=${domain_name}/' custom_data.sh
    - sed -i '67s/.*/admin_login=${admin_login}/' custom_data.sh
    - sed -i '68s/.*/CEGID_API_CLIENT_ID=${CEGID_API_CLIENT_ID}/' custom_data.sh
    - sed -i '69s/.*/CEGID_API_CLIENT_SECRET=${CEGID_API_CLIENT_SECRET}/' custom_data.sh
    - sed -i '70s/.*/CEGID_API_CONSUMER_ID=${CEGID_API_CONSUMER_ID}/' custom_data.sh
    - sed -i '71s/.*/CEGID_API_CONSUMER_SECRET=${CEGID_API_CONSUMER_SECRET}/' custom_data.sh
    - sed -i '72s/.*/CEGID_DATA_ACCESS_API_KEY=${CEGID_DATA_ACCESS_API_KEY}/' custom_data.sh
    - sed -i '73s/.*/CEGID_DATA_ACCESS_API_SECRET=${CEGID_DATA_ACCESS_API_SECRET}/' custom_data.sh
    - sed -i '74s/.*/PAPPERS_API_TOKEN=${PAPPERS_API_TOKEN}/' custom_data.sh
    - sed -i '75s/.*/SILAE_WS_LOGIN=${SILAE_WS_LOGIN}/' custom_data.sh
    - sed -i '76s/.*/SILAE_WS_PASSWORD=${SILAE_WS_PASSWORD}/' custom_data.sh
    - sed -i '77s/.*/SILAE_SITE_LOGIN=${SILAE_SITE_LOGIN}/' custom_data.sh
    - sed -i '78s/.*/SILAE_SITE_PASSWORD=${SILAE_SITE_PASSWORD}/' custom_data.sh
    - sed -i '79s/.*/MICROSOFT_GRAPH_CLIENT_ID=${MICROSOFT_GRAPH_CLIENT_ID}/' custom_data.sh
    - sed -i '80s/.*/MICROSOFT_GRAPH_CLIENT_SECRET=${MICROSOFT_GRAPH_CLIENT_SECRET}/' custom_data.sh
    - sed -i '81s/.*/MICROSOFT_GRAPH_TENANT_ID=${MICROSOFT_GRAPH_TENANT_ID}/' custom_data.sh
    - sed -i '82s/.*/MICROSOFT_GRAPH_SITE_ID=${MICROSOFT_GRAPH_SITE_ID}/' custom_data.sh
    - sed -i '83s/.*/APP_SECRET=$(cat /dev/urandom | tr -dc '"'"'a-zA-Z0-9'"'"' | fold -w 48 | head -n 1)/' custom_data.sh
    - sed -i '84s/.*/JWT_PASSPHRASE=$(cat /dev/urandom | tr -dc '"'"'a-zA-Z0-9'"'"' | fold -w 48 | head -n 1)/' custom_data.sh
  


  cache:
    key: terraform
    paths:
      - .terraform

terraform_validate:
  stage: validate
  script:
    - terraform validate

terraform_plan:
  stage: plan
  script: 
    - terraform plan --out plan
  artifacts:
    paths:
      - plan

terraform_apply:
  stage: apply
  script:
    - terraform apply --auto-approve plan
  when: manual
  allow_failure: false
  only:
    refs:
      - main