stages:
  - validate
  - plan
  - apply

default:
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - /usr/bin/env
      - "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

  before_script:
    - terraform init
    - sed -i "38s|.*|git_token=${git_token}|" custom_data.sh
    - sed -i "39s|.*|git_username=${git_username}|" custom_data.sh
    - sed -i "40s|.*|git clone https://\$git_username:\$git_token@github.com/Impulsa-fr/back-end.git|" custom_data.sh
    - sed -i "41s|.*|git clone https://\$git_username:\$git_token@github.com/Impulsa-fr/front-end.git|" custom_data.sh
    
    - cat custom_data.sh
    - password=$( (tr -dc A-Za-z0-9 < /dev/urandom || true) | head -c 16 )
    - echo "admin_password:${password}" >> playbook/vars.yml  
    - echo "DBPASS=${password}" >> custom_data.sh #60

    - echo "URI_FRONT_HOME=${URI_FRONT_HOME}" >> custom_data.sh #61
    - echo "URI_API=${URI_API}" >> custom_data.sh #62
    - echo "DB_LOGIN=${DB_LOGIN}" >> custom_data.sh #63
    - echo "DB_NAME=${DB_NAME}" >> custom_data.sh #64
  
    
    - echo "domain_name=${domain_name}" >> custom_data.sh #65
    - echo "admin_login=${admin_login}" >> custom_data.sh #66
    - echo "CEGID_API_CLIENT_ID=${CEGID_API_CLIENT_ID}" >> custom_data.sh #67
    - echo "CEGID_API_CLIENT_SECRET=${CEGID_API_CLIENT_SECRET}" >> custom_data.sh #68
    - echo "CEGID_API_CONSUMER_ID=${CEGID_API_CONSUMER_ID}" >> custom_data.sh #69
    - echo "CEGID_API_CONSUMER_SECRET=${CEGID_API_CONSUMER_SECRET}" >> custom_data.sh #70
    - echo "CEGID_DATA_ACCESS_API_KEY=${CEGID_DATA_ACCESS_API_KEY}" >> custom_data.sh #71
    - echo "CEGID_DATA_ACCESS_API_SECRET=${CEGID_DATA_ACCESS_API_SECRET}" >> custom_data.sh #72
    - echo "PAPPERS_API_TOKEN=${PAPPERS_API_TOKEN}" >> custom_data.sh #73
    - echo "SILAE_WS_LOGIN=${SILAE_WS_LOGIN}" >> custom_data.sh #74
    - echo "SILAE_WS_PASSWORD=${SILAE_WS_PASSWORD}" >> custom_data.sh #75
    - echo "SILAE_SITE_LOGIN=${SILAE_SITE_LOGIN}" >> custom_data.sh #76
    - echo "SILAE_SITE_PASSWORD=${SILAE_SITE_PASSWORD}" >> custom_data.sh #77
    - echo "MICROSOFT_GRAPH_CLIENT_ID=${MICROSOFT_GRAPH_CLIENT_ID}" >> custom_data.sh #78
    - echo "MICROSOFT_GRAPH_CLIENT_SECRET=${MICROSOFT_GRAPH_CLIENT_SECRET}" >> custom_data.sh #79
    - echo "MICROSOFT_GRAPH_TENANT_ID=${MICROSOFT_GRAPH_TENANT_ID}" >> custom_data.sh #80
    - echo "MICROSOFT_GRAPH_SITE_ID=${MICROSOFT_GRAPH_SITE_ID}" >> custom_data.sh #81

    - echo "APP_SECRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 48 | head -n 1)" >> custom_data.sh #82
    - echo "JWT_PASSPHRASE=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 48 | head -n 1)" >> custom_data.sh #83 
    
    - sed -n '32,55p' custom_data.sh >> .env


  cache:
    key: terraform
    paths:
      - .terraform

terraform_validate:
  stage: validate
  script:
    - terraform validate

terraform_plan:
  stage: plan
  script: 
    - terraform plan --out plan
  artifacts:
    paths:
      - plan

terraform_apply:
  stage: apply
  script:
    - terraform apply --auto-approve plan
  when: manual
  allow_failure: false
  only:
    refs:
      - main